name: Ping auto-pots every minute

on:
  schedule:
    - cron: "* * * * *"  # every minute
  workflow_dispatch:      # allows manual trigger too

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call auto-pots.vercel.app
        run: |
          curl -s https://auto-pots.vercel.app/
