name: Ping auto-posts every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: # allows manual trigger too

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call auto-posts-tau.vercel.app
        run: |
          curl -s https://auto-posts-tau.vercel.app/
